import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

import "/public/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gavin Xue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js" />
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
